# Main build configuration
[build]
  command = "npm run build"
  publish = "dist/client"
  
  # All environment variables are managed in Netlify UI
  # Required variables:
  # - PUBLIC_SUPABASE_URL
  # - PUBLIC_SUPABASE_ANON_KEY

# Development settings
[dev]
  command = "npm run dev"
  framework = "astro"
  
# All requests are handled by the SSR function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200

# Cache static assets for better performance
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"