[build]
  command = "npm run build"
  publish = "dist/client"
  
  # Environment variables are now set in Netlify UI

[dev]
  command = "npm run dev"
  framework = "astro"
  
# Let Astro's built-in Netlify adapter handle the routing
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200

# Set cache headers for static assets
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"