[build]
  base = "board-portal"
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  framework = "astro"
  
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200