[build]
  base = "board-portal"
  command = "npm run build"
  publish = "dist/client"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  framework = "astro"
  
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200
  
# Make sure static assets are served correctly
[[redirects]]
  from = "/_astro/*"
  to = "/_astro/:splat"
  status = 200