[build]
  command = "cd board-portal && npm run build"
  publish = "board-portal/dist"
  functions = "board-portal/netlify/functions"

[dev]
  command = "cd board-portal && npm run dev"
  framework = "astro"
  
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200